version: '3'
services:
  light-traefik:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - .:/usr/src/app
      - /usr/src/app/node_modules
    network_mode: bridge
    environment:
      - NODE_ENV=development